#!/usr/bin/env sh

# A wrapper around the Nim compiler to allow for easy scripting of Nim. Puts
# all temporary files in a temporary directory and cleans up after itself.
#
# Usage:
#  - add "#!/usr/bin/env nimrun" at the beginning of your script
#  - execute the nim file with it, for example, "nimrun file.nim args"
#
# Possible future extentions:
#  - cache compilation results for a while
#  - configurable temporary directory
#
# Author: Flaviu Tamas <tamas.flaviu@gmail.com>

output=$(mktemp -d)
trap "rm -rf $output" EXIT

nim c --verbosity:0 \
      --hints:off \
      --out:"$output/executable" \
      --nimcache:"$output/" \
      "$1"

# first argument is filename, not needed any more
shift

$output/executable $*

exit $?
